services:
  fahrendra-khoirul:
    build:
      context: .
    expose:
      - "80"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    external: true

volumes:
  caddy_data:
  caddy_config: